FROM nvcr.io/nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04

RUN apt-get update && yes|apt-get upgrade
RUN apt-get install -y wget pkg-config

# RUN apt update
# RUN apt --fix-broken install
# RUN #!/bin/bash && source ~/.bashrc
#RUN conda update --all

ARG DEBIAN_FRONTEND=noninteractive

ENV APT_INSTALL="apt-get install -y --no-install-recommends"

RUN apt-get update && $APT_INSTALL \
         build-essential \
         cmake \
         git \
         openssh-client \
         curl \
         vim-gtk \
         tmux \
         zip \
         unzip \
         ca-certificates \
         libjpeg-dev \
         libopenexr-dev \
         libpng-dev \
         sudo 

ENV PIP3I="python3 -m pip install"

RUN $APT_INSTALL \
    python3 python3-pip python3-dev python3-tk python3-pil.imagetk python3-setuptools

RUN python3 -m pip install torch==1.4.0 torchvision==0.5.0

RUN /bin/bash -c "python3 -m pip install --upgrade pip && \
    python3 -m pip install \
    opencv-python \
    scikit-image \
    matplotlib \
    imageio \
    black \
    isort \
    comet_ml \
    sklearn \
    pandas \ 
    transforms3d"

ENTRYPOINT ["/pointillism/build_and_install.sh"]
